#!/usr/bin/env bash
set -e # halt script on error

gem install jekyll-paginate
bundle update
bundle exec jekyll build
#ls ./_site
#cat ./_site/index.html
#bundle exec htmlproof ./_site -checks-to-ignore LinkCheck